# Generated by Django 5.0.6 on 2024-06-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_username',
            field=models.CharField(default='odniglaziy_Jackie_Chan', max_length=200, verbose_name='Имя пользователя в телеграмме'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Чат id пользователя в телеграмме'),
        ),
    ]
