# Generated by Django 5.0.6 on 2024-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_time_alter_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='telegramm_username',
            field=models.CharField(default='odnoglaziy_Jackie_Chan', max_length=200, verbose_name='Имя пользователя в телеграмме'),
            preserve_default=False,
        ),
    ]
