# Generated by Django 5.0.6 on 2024-06-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_telegramm_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='telegramm_username',
            new_name='telegram_username',
        ),
    ]
